using UnityEngine;
using System.Collections;
//	using System.IO.Ports;

public class s_input_pep_redbox : MonoBehaviour {
		
/*	public SerialPort stream = new SerialPort("/dev/tty.usbmodem621", 9600);	// open serial Mac = /dev/tty.usbmodem621, PC = COM3 or COM4 ; baud = 9600
	
	private static s_input_pep_redbox _instance;								// transform to class, script must be unique --> SINGLETON
	private float f_pressure_inter;
	
	void Start () {
		_instance = this;														// reference to itself so that the script is accessible from any other script --> SINGLETON
		stream.Open(); 															// Open the Serial Stream.
	}

	void Update () {
		string value = stream.ReadLine(); 										// Read the information
		f_pressure_inter = float.Parse (value);
		f_pressure_inter -= 99000f;
		f_pressure_inter *= 0.01f;
		s_input.f_pressure = f_pressure_inter;
	}
	
	public static s_input_pep_redbox GetSceneInstance ()
	{
		return _instance;														// gives access to this unique instance for this script from anywhere else
	}
*/}